env: _11_vs_11_hard_stochastic # google research football

env_args:
  dense_reward: False
  write_full_episode_dumps: False
  write_goal_dumps: False
  dump_freq: 1000
  render: False
  n_agents: 10
  n_enemies: 11
  episode_limit: 500
  time_step: 0
  env_name: "11_vs_11_hard_stochastic"
  stacked: False # return the 4 stacked observations for "pixels", "pixels_gray" or "extracted"
  representation: "raw"
  rewards: "scoring"
  logdir: "../results/replays"
  write_video: False
  number_of_right_players_agent_controls: 0
  sampling: False
  seed: 0

batch_size: 32
test_greedy: True
test_nepisode: 32
test_interval: 10000
log_interval: 2000
runner_log_interval: 2000
learner_log_interval: 2000
t_max: 10050000
backward_learning: False