env: academy_3_vs_1_with_keeper # google research football

env_args:
  dense_reward: False
  write_full_episode_dumps: False
  write_goal_dumps: False
  dump_freq: 1000
  render: False
  n_agents: 3
  n_enemies: 2
  episode_limit: 300
  time_step: 0
  env_name: "academy_3_vs_1_with_keeper"
  stacked: False
  representation: "raw"
  rewards: "scoring"
  logdir: "../results/replays"
  write_video: False
  number_of_right_players_agent_controls: 0
  sampling: False
  seed: 0

batch_size: 32
test_greedy: True
test_nepisode: 32
test_interval: 10000
log_interval: 2000
runner_log_interval: 2000
learner_log_interval: 2000
t_max: 10050000
backward_learning: False